jobs:
  - pre-flight-checks
  - install-ui-dependencies:
      requires:
        - pre-flight-checks
  - go-mod-download:
      requires:
        - pre-flight-checks
  - build-go-dev:
      requires:
        - go-mod-download
  - test-ui:
      requires:
        - install-ui-dependencies
        - build-go-dev
  - test-go:
      requires:
        - build-go-dev
  - test-go-race:
      requires:
        - build-go-dev
